# Generated by Django 5.0.4 on 2024-04-08 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_product_category_remove_product_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scan',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='scan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, to='api.scan'),
            preserve_default=False,
        ),
    ]
